# Attributes are defined in test-fixtures/attributes/attributes-referenced.yaml
name: project1
clonePath: "/{{foo}}"
sparseCheckoutDirs:
  - /FOO
  - "/{{bar}}"
git:
  checkoutFrom:
    revision: "{{foo}}"
  remotes:
    "foo": "{{bar}}"
    "{{foo}}{{bar}}": "{{bar}}{{foo}}"